FROM node:16.14-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./


RUN npm install

COPY . .

RUN npm run build

FROM node:16.14-alpine AS artifact

WORKDIR /app

COPY --from=build /usr/src/app/dist ./
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY .env.k8s ./.env

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "node", "main" ]
