version: '3.4'

services:
  dev:
    container_name: saloon_api_dev
    image: saloon-api-dev:1.0.0
    env_file:
      - .env
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 4000:4000
      - 9229:9229
    networks:
      - saloon-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  prod:
    container_name: saloon_api_prod
    image: saloon-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - saloon-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  saloon-network:
    driver: bridge
