FROM node:14 AS build

WORKDIR /usr/src/app

COPY package*.json ./


RUN npm install

COPY . .

RUN npm run build

FROM public.ecr.aws/lambda/nodejs:14 as artifact

COPY --from=build /usr/src/app/dist ${LAMBDA_TASK_ROOT}
COPY --from=build /usr/src/app/node_modules ${LAMBDA_TASK_ROOT}/node_modules
COPY .env.lambda ${LAMBDA_TASK_ROOT}/.env

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda.handler" ]
