apiVersion: v1
kind: Service
metadata:
  namespace: orange
  name: orange-api
spec:
  selector:
    app: orange-api
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
  type: NodePort
