apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-orange-api
  release: dev
namespace: dev-orange
resources:
  - ../../base
images:
  - name: saas-orange-api
    newName: 790723374872.dkr.ecr.us-east-2.amazonaws.com/orange-uat
    newTag: saas-web-api-dev-1c1973f
