apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: qa-
commonLabels:
  app: qa-stride-api
  release: qa
namespace: qa-stride
resources:
- ../../base

images:
- name: saas-stride-api
  newName: 938631482679.dkr.ecr.us-west-1.amazonaws.com/stride-qa
  newTag: stride-learning-api-server-qa-c1b349cf42c1ac5af589698bbf75f14417dae98f
